@gameId = 45f4f9e6-1c97-47b8-9318-b0efcda7fda1

### Generate Board
POST localhost:8086/api/games
Content-Type: application/json

{
  "players": [
    "642999ad-c546-40b6-876c-1048971c7942",
    "cf36d3e1-a1e0-4c18-89eb-95fa76fc81ee"
  ],
  "settings": {
    "boardSize": 3
  }
}

### Next turn
POST localhost:8086/api/games/{{gameId}}/move
Content-Type: application/json

{
  "row": 2,
  "col": 0,
  "gameId": "{{gameId}}",
  "playerId": "642999ad-c546-40b6-876c-1048971c7942"
}

### Get Game
GET localhost:8086/api/games/{{gameId}}
Accept: application/json