### 1) Haal JWT-token op via Keycloak (PASSWORD GRANT)
POST http://localhost:8080/auth/realms/moko/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = user-service &
client_secret = ZmXSd2mIzB6hsLrybeD3gH0c11vPwrej &
username = mathias &
password = loginmathias &
scope = openid

> {%
    client.global.set("access_token", response.body.access_token);
%}

### 2) GET /api/profiles/me
GET http://localhost:8080/api/user-service/profiles/me
Authorization: Bearer {{access_token}}
