### Create tic tac toe game
POST http://localhost:80/tic-tac-toe-service/api/games
Content-Type: application/json

{
  "players": [
    "642999ad-c546-40b6-876c-1048971c7942",
    "cf36d3e1-a1e0-4c18-89eb-95fa76fc81ee"
  ],
  "settings": {
    "boardSize": 3
  }
}

### Create bot tic tac toe game
POST http://localhost:80/tic-tac-toe-service/api/games?aiPlayer=true
Content-Type: application/json

{
  "players": [
    "51415b39-84d2-4cbd-b4fd-5a4f83231abd",
    "00000000-0000-0000-0000-000000000000"
  ],
  "settings": {
    "boardSize": 3
  }
}