### 1) JWT Token (mathias)
POST http://localhost:8180/realms/moko/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password &
client_id=communication-service &
client_secret=cXwsnvyHm2NquygtuDb3QWTLjs9PUOzW &
username=mathias &
password=loginmathias &
scope=openid

> {%
    client.global.set("chat_token", response.body.access_token);
%}

### 1) JWT Token (kaj)
POST http://localhost:8180/realms/moko/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password &
client_id=communication-service &
client_secret=cXwsnvyHm2NquygtuDb3QWTLjs9PUOzW &
username=kaj &
password=loginkaj &
scope=openid

> {%
    client.global.set("kaj_Token", response.body.access_token);
%}

### 2) Send message to BOT chat channel
POST http://localhost:8082/api/chat/bot/user123-tictactoe
Authorization: Bearer {{chat_token}}
Content-Type: application/json

{
  "content": "Hoe speel ik tic tac toe?"
}

> {%
    client.global.set("bot_reference", "user123-tictactoe");
%}



### 3) Send second message to BOT
POST http://localhost:8082/api/chat/bot/{{bot_reference}}
Authorization: Bearer {{chat_token}}
Content-Type: application/json

{
  "content": "Wat is de beste openingszet?"
}



### 4) GET BOT chat messages
GET http://localhost:8082/api/chat/bot/{{bot_reference}}
Authorization: Bearer {{chat_token}}



### 5) GET BOT chat messages since timestamp
GET http://localhost:8082/api/chat/bot/{{bot_reference}}?since=2025-01-01T00:00:00Z
Authorization: Bearer {{chat_token}}

### 6) Send message to LOBBY chat
POST http://localhost:8082/api/chat/lobby/e943f180-eaba-4de3-9d12-eee13a25c1b5
Authorization: Bearer {{chat_token}}
Content-Type: application/json

{
  "content": "Hey iedereen!"
}

> {%
    client.global.set("lobby_id", "e943f180-eaba-4de3-9d12-eee13a25c1b5");
%}



### 7) Send second message to LOBBY
POST http://localhost:8082/api/chat/lobby/{{lobby_id}}
Authorization: Bearer {{kaj_Token}}
Content-Type: application/json

{
  "content": "Wanneer starten we?"
}



### 8) GET lobby chat messages
GET http://localhost:8082/api/chat/lobby/{{lobby_id}}
Authorization: Bearer {{chat_token}}

### health check
GET http://localhost:8082/actuator/health

### testing notifications
POST http://localhost:8082/api/notifications/test

###########################################################
### FRIENDS CHAT TESTS
###########################################################

### 9) Send message to FRIEND (replace UUID with actual friend's user ID)
# Note: You need to be friends with this user in social-service first!
POST http://localhost:8082/api/chat/friends/{{friend_id}}
Authorization: Bearer {{chat_token}}
Content-Type: application/json

{
  "content": "Hey! Hoe gaat het?"
}

### 10) Get friend chat messages
GET http://localhost:8082/api/chat/friends/{{friend_id}}
Authorization: Bearer {{chat_token}}

### 11) Get friend chat messages since timestamp
GET http://localhost:8082/api/chat/friends/{{friend_id}}?since=2025-01-01T00:00:00Z
Authorization: Bearer {{chat_token}}

### 12) Send message as the other friend (kaj to mathias)
POST http://localhost:8082/api/chat/friends/{{mathias_id}}
Authorization: Bearer {{kaj_Token}}
Content-Type: application/json

{
  "content": "Goed! Zin in een potje?"
}

### 13) Get chat as kaj - should see both messages
GET http://localhost:8082/api/chat/friends/{{mathias_id}}
Authorization: Bearer {{kaj_Token}}
Authorization: Bearer {{chat_token}}

### get unread notifications
GET http://localhost:8082/api/notifications/unread
Authorization: Bearer {{chat_token}}
