name: moko_local_frontend

services:
  frontend-platform:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/platform-frontend:main-latest
    restart: always
    pull_policy: always
    profiles: ["frontend_platform"]
    environment:
      VITE_AUTH_URL: http://localhost:8180
      VITE_AUTH_REALM: moko
      VITE_AUTH_CLIENT: platform-frontend

      VITE_USER_SERVICE: http://localhost:8080/api/profiles
      VITE_LIBRARY_SERVICE: http://localhost:8080/api/library
      VITE_SOCIAL_SERVICE: http://localhost:8083/api/friends
      VITE_SESSION_SERVICE: http://localhost:8081/api/lobbies
      VITE_GAMES_SERVICE: http://localhost:8084/api/games
      VITE_STORE_SERVICE: http://localhost:8085/api/store/games
      VITE_SESSION_SOCKET: http://localhost:8081
    ports:
      - "5173:80"

  frontend-tic-tac-toe:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/tic-tac-toe-frontend:main-latest
    restart: always
    pull_policy: always
    profiles: ["frontend_tic_tac_toe"]
    environment:
      VITE_AUTH_URL: http://localhost:8180
      VITE_AUTH_REALM: moko
      VITE_AUTH_CLIENT: tic-tac-toe-frontend

      VITE_TIC_TAC_TOE_SERVICE: http://localhost:8086/api/games
      VITE_USER_SERVICE: http://localhost:8080/api/profiles
    ports:
      - "5174:80"

  frontend-checkers:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/checkers-frontend:main-latest
    restart: always
    pull_policy: always
    profiles: ["frontend_checkers"]
    environment:
      VITE_AUTH_URL: http://localhost:8180
      VITE_AUTH_REALM: moko
      VITE_AUTH_CLIENT: checkers-frontend

      VITE_CHECKERS_SERVICE: http://localhost:8087/api/games
      VITE_USER_SERVICE: http://localhost:8080/api/profiles
    ports:
      - "5175:80"