name: moko_local_frontend

services:
  frontend-platform:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/platform-frontend:main-latest
    restart: always
    pull_policy: always
    profiles: ["frontend-platform"]
    environment:
      VITE_AUTH_URL: http://localhost/auth
      VITE_AUTH_REALM: moko
      VITE_AUTH_CLIENT: platform-frontend

      VITE_USER_SERVICE: http://localhost/user-service/api/profiles
      VITE_LIBRARY_SERVICE: http://localhost/user-service/api/library
      VITE_SOCIAL_SERVICE: http://localhost/social-service/api/friends
      VITE_SESSION_SERVICE: http://localhost/session-service/api/lobbies
      VITE_GAMES_SERVICE: http://localhost/game-service/api/games
    ports:
      - "5173:80"
    networks:
      - moko_frontend

  frontend-tic-tac-toe:
    image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/tic-tac-toe-frontend:main-latest
    restart: always
    pull_policy: always
    profiles: ["frontend-tic-tac-toe"]
    environment:
      VITE_AUTH_URL: http://localhost/auth
      VITE_AUTH_REALM: moko
      VITE_AUTH_CLIENT: tic-tac-toe-frontend

      VITE_TIC_TAC_TOE_SERVICE: http://localhost/tic-tac-toe-service/api/games
      VITE_USER_SERVICE: http://localhost/user-service/api/profiles
    ports:
      - "5174:80"
    networks:
      - moko_frontend