name: moko_local_game_services

services:
    service-tic-tac-toe:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/tic-tac-toe-service:main-latest
        restart: always
        pull_policy: always
        profiles: ["tic-tac-toe"]
        environment:
            SPRING_DATA_REDIS_HOST: app-redis
            SPRING_DATA_REDIS_PORT: 6379
            SPRING_DATA_REDIS_DATABASE: 0
            SPRING_DATA_REDIS_PASSWORD: password

            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            GAME_SERVICE_URL: http://host.docker.internal:8084
            BUSINESS_AI_URL: https://team3.techtitans.be

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs

            AI_URL: https://team3.techtitans.be

            GAME_BACKEND_URL: http://host.docker.internal:8086
            GAME_FRONTEND_URL: http://localhost:5174/tic-tac-toe/game
        ports:
            - "8086:8086"
        healthcheck:
            test:
                ["CMD", "wget", "-qO-", "http://localhost:8086/actuator/health"]
            interval: 1m
            timeout: 15s
            retries: 5
            start_period: 5m
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc
        depends_on:
          - service-games
          - service-store

    service-checkers:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/checkers-service:main-latest
        restart: always
        pull_policy: always
        profiles: ["checkers"]
        environment:
            SPRING_DATA_REDIS_HOST: app-redis
            SPRING_DATA_REDIS_PORT: 6379
            SPRING_DATA_REDIS_DATABASE: 0
            SPRING_DATA_REDIS_PASSWORD: password

            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            GAME_SERVICE_URL: http://host.docker.internal:8084

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/auth/realms/moko/protocol/openid-connect/certs

            AI_URL: https://team3.techtitans.be

            GAME_BACKEND_URL: http://host.docker.internal:8087
            GAME_FRONTEND_URL: http://localhost:5175/checkers/game
        ports:
            - "8087:8087"
        healthcheck:
            test:
                ["CMD", "wget", "-qO-", "http://localhost:8087/actuator/health"]
            interval: 1m
            timeout: 15s
            retries: 5
            start_period: 5m
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc
        depends_on:
          - service-games
          - service-store