name: moko_local_infrastructure

services:
    app-postgres:
        image: postgres:17.7-alpine
        restart: always
        environment:
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "moko"
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5443:5432"
        networks:
            - moko_backend
        volumes:
            - moko_postgres_data:/var/lib/postgresql/data
            - ./init-scripts/sql:/docker-entrypoint-initdb.d/

    app-rabbitmq:
        image: rabbitmq:4.2-management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: "user"
            RABBITMQ_DEFAULT_PASS: "password"
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - moko_backend
        volumes:
            - moko_rabbitmq_all:/var/lib/rabbitmq/
            - moko_rabbitmq_all:/var/log/rabbitmq/

    app-redis:
        image: redis:8.4.0-alpine
        ports:
            - "6379:6379"
        command:
            - redis-server
            - --requirepass password
        networks:
            - moko_backend
        volumes:
            - moko_redis_all:/data

    idp-mysql:
        image: mysql:9.5
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "keycloak"
            MYSQL_USER: "keycloak"
            MYSQL_PASSWORD: "password"
        ports:
            - "3307:3306"
        volumes:
            - moko_mysql_data:/var/lib/mysql
        networks:
            - moko_kc

    idp-keycloak:
        image: quay.io/keycloak/keycloak:26.4
        restart: always
        environment:
            KEYCLOAK_ADMIN: "admin"
            KEYCLOAK_ADMIN_PASSWORD: "admin"
            KC_DB: "mysql"
            KC_DB_URL_HOST: "idp-mysql"
            KC_DB_URL_DATABASE: "keycloak"
            KC_DB_USERNAME: "keycloak"
            KC_DB_PASSWORD: "password"
        command:
            - start-dev
            - --import-realm
        volumes:
            - ./init-scripts/keycloak-import:/opt/keycloak/data/import
        ports:
            - "8180:8080"
        depends_on:
            - idp-mysql
        networks:
            - moko_kc

volumes:
    moko_postgres_data:
    moko_rabbitmq_all:
    moko_redis_all:
    moko_mysql_data:
