name: moko_local_backend_services

services:
    service-user:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/user-service:main-latest
        restart: no
        pull_policy: always
        profiles: ["user"]
        ports:
            - "8089:8089"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://app-postgres:5432/moko?currentSchema=user_service
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs

            GAME_SERVICE_URL: http://host.docker.internal:8084
            CHAT_SERVICE_URL: http://host.docker.internal:8082
        healthcheck:
            test:
                ["CMD", "wget", "-qO-", "http://localhost:8089/actuator/health"]
            interval: 1m
            timeout: 15s
            retries: 5
            start_period: 5m
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc

    service-session:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/session-service:main-latest
        restart: no
        pull_policy: always
        profiles: ["session"]
        ports:
            - "8081:8081"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://app-postgres:5432/moko?currentSchema=session_service
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs

            USER_SERVICE_URL: http://host.docker.internal:8089
            SOCIAL_SERVICE_URL: http://host.docker.internal:8083
            GAME_SERVICE_URL: http://host.docker.internal:8084
            CHAT_SERVICE_URL: http://host.docker.internal:8082
        healthcheck:
            test:
                ["CMD", "wget", "-qO-", "http://localhost:8081/actuator/health"]
            interval: 1m
            timeout: 15s
            retries: 5
            start_period: 5m
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc

    service-social:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/social-service:main-latest
        restart: no
        pull_policy: always
        profiles: ["social"]
        ports:
            - "8083:8083"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://app-postgres:5432/moko?currentSchema=social_service
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs

            USER_SERVICE_URL: http://host.docker.internal:8089
            CHAT_SERVICE_URL: http://host.docker.internal:8082
        healthcheck:
            test:
                ["CMD", "wget", "-qO-", "http://localhost:8083/actuator/health"]
            interval: 1m
            timeout: 15s
            retries: 5
            start_period: 5m
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc

    service-games:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/games-service:main-latest
        restart: no
        pull_policy: always
        profiles: ["games"]
        ports:
            - "8084:8084"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://app-postgres:5432/moko?currentSchema=games_service
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
            SPRING_SQL_INIT_MODE: never
            SPRING_SQL_DATA_FILE: docker.sql

            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            STORE_SERVICE_URL: http://host.docker.internal:8085

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs
        healthcheck:
            test:
                ["CMD", "wget", "-qO-", "http://localhost:8084/actuator/health"]
            interval: 1m
            timeout: 15s
            retries: 5
            start_period: 5m
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc

    service-store:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/store-service:main-latest
        restart: no
        pull_policy: always
        profiles: ["store"]
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://app-postgres:5432/moko?currentSchema=store_service
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
            SPRING_SQL_INIT_MODE: never

            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs

            USER_SERVICE_URL: http://host.docker.internal:8089
            GAME_SERVICE_URL: http://host.docker.internal:8084
            CHAT_SERVICE_URL: http://host.docker.internal:8082
        ports:
            - "8085:8085"
        healthcheck:
            test:
                ["CMD", "wget", "-qO-", "http://localhost:8085/actuator/health"]
            interval: 1m
            timeout: 15s
            retries: 5
            start_period: 5m
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc

    service-communication:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/communication-service:main-latest
        restart: no
        pull_policy: always
        profiles: ["communication"]
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://app-postgres:5432/moko?currentSchema=communication_service
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs

            SESSION_SERVICE_URL: http://host.docker.internal:8081
            USER_SERVICE_URL: http://host.docker.internal:8089
            SOCIAL_SERVICE_URL: http://host.docker.internal:8083

            SPRING_MAIL_USERNAME: mokogamesbe@gmail.com
            SPRING_MAIL_PASSWORD: alofzkyfupctrpmw
            BOT_SERVICE_API_KEY: POjzhHKDCBDMXkf0Lly8yW8YaCTjZCeh4_UZw_THWjM
        ports:
            - "8082:8082"
        healthcheck:
            test:
                ["CMD", "wget", "-qO-", "http://localhost:8082/actuator/health"]
            interval: 1m
            timeout: 15s
            retries: 5
            start_period: 5m
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc
    service-socket:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/socket-service:main-latest
        restart: no
        pull_policy: always
        profiles: ["socket"]
        environment:
            SPRING_RABBITMQ_HOST: app-rabbitmq
            SPRING_RABBITMQ_PORT: 5672
            SPRING_RABBITMQ_USERNAME: user
            SPRING_RABBITMQ_PASSWORD: password

            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs
        ports:
            - "8090:8090"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend
            - moko_kc
    service-acl:
      image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/game-acl-service:main-latest
      restart: no
      pull_policy: always
      profiles: [ "acl" ]
      environment:
        SPRING_RABBITMQ_HOST: app-rabbitmq
        SPRING_RABBITMQ_PORT: 5672
        SPRING_RABBITMQ_USERNAME: user
        SPRING_RABBITMQ_PASSWORD: password

        SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://idp-keycloak:8080/realms/moko/protocol/openid-connect/certs

        GAME_SERVICE_URL: http://host.docker.internal:8084
        ACL_CONFIG_BACKEND_URL: http://host.docker.internal:8088

        CHESS_INFO_BACKEND_URL: http://host.docker.internal:8080
      ports:
        - "8088:8088"
      healthcheck:
        test:
          [ "CMD", "wget", "-qO-", "http://localhost:8088/actuator/health" ]
        interval: 1m
        timeout: 15s
        retries: 5
        start_period: 5m
      extra_hosts:
        - "host.docker.internal:host-gateway"
      networks:
        - moko_backend
        - moko_kc
