name: black_box_chess

services:
    app_chessgame_front:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/demo-content/chessgame/front:latest
        profiles: ["chess"]
        pull_policy: always
        ports:
            - "3333:80"
        networks:
            - kdg-backend
            - moko_backend
        depends_on:
            - app_chessgame_back
            - app-rabbitmq
            - app_postgres

    app_chessgame_back:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/demo-content/chessgame/back:latest
        profiles: ["chess"]
        pull_policy: always
        ports:
            - "8080:8080"
        networks:
            - kdg-backend
            - moko_backend
        depends_on:
            - app_postgres
            - app-rabbitmq
        environment:
            - GAME_REGISTRATION_ID=8496c496-a884-48ed-9bb3-7c3aa50fb8ca
            - DATASOURCE_URL=jdbc:postgresql://app_postgres:5432/postgres
            - DATASOURCE_USER=user
            - DATASOURCE_PASSWORD=password
            - RABBIT_HOST=app-rabbitmq
            - RABBIT_PORT=5672
            - RABBIT_USER=user
            - RABBIT_PASSWORD=password

    app_postgres:
        image: postgres:17.6-alpine
        profiles: ["chess"]
        restart: always
        environment:
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "postgres"
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5444:5432"
        networks:
            - kdg-backend
            - moko_backend
        volumes:
            - ./postgresql/data:/var/lib/postgresql
            - ./init-scripts/sql:/docker-entrypoint-initdb.d

networks:
    kdg-backend:
        name: kdg-back-network
        driver: bridge
