name: moko_local_chatbot

services:
    db:
        image: postgres:15
        container_name: ai_chatbot_db
        restart: always
        profiles: ["chatbot"]
        environment:
            POSTGRES_USER: aiuser
            POSTGRES_PASSWORD: aipassword
            POSTGRES_DB: aichatbot
        ports:
            - "6432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        restart: unless-stopped
        profiles: ["chatbot"]
        environment:
            OLLAMA_NO_DAEMON: "true"
        command: serve
        ports:
            - "11434:11434"
        volumes:
            - ollama_data:/root/.ollama

    ollama-init:
        image: ollama/ollama:latest
        profiles: ["chatbot"]
        depends_on:
            - ollama
        entrypoint: ["/bin/sh", "-c"]
        command: |
            echo "Waiting for Ollama..."
            until ollama list >/dev/null 2>&1; do
            sleep 1
            done

            ollama pull nomic-embed-text
            ollama pull gemma3:4b
        volumes:
            - ollama_data:/root/.ollama

    fastapi:
        image: registry.gitlab.com/kdg-ti/integratieproject-j3/teams-25-26/team22/local-development/chatbot:latest
        container_name: ai_chatbot_service
        profiles: ["chatbot"]
        restart: always
        depends_on:
            - db
            - ollama
        environment:
            DATABASE_URL: postgresql+psycopg2://aiuser:aipassword@db:5432/aichatbot
            OLLAMA_BASE_URL: http://ollama:11434
            GEMINI_API_KEY: AIzaSyCLrMOK3X71h6mviAzDAZ-e36_P-ZlhRHw
        ports:
            - "3334:8000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - moko_backend

volumes:
    db_data:
    ollama_data:
