### Create Checkers game
POST localhost/checkers-service/api/games
Content-Type: application/json

{
  "players": [
    "642999ad-c546-40b6-876c-1048971c7942",
    "cf36d3e1-a1e0-4c18-89eb-95fa76fc81ee"
  ]
}

### Get Checkers game
GET localhost/checkers-service/api/games/b9e08346-816e-4670-ba3c-6f98b709460c